# https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "npm" 
    directory: "ember-flight-icons/" 
    versioning-strategy: increase
    schedule:
      interval: "daily"
    allow: 
      - dependency-name: "@hashicorp/*"
  - package-ecosystem: "npm" 
    directory: "website/" 
    versioning-strategy: increase
    schedule:
      interval: "daily"
    allow: 
      - dependency-name: "@hashicorp/*"

