/*
this script will:
- clone the dist folder that was generated by the build step
- generate the bundles for every "format" that we want to distribute (the one below is just an example)
  - Ember
  - SVGs
  - React (??)
  - CSS (??)
  - others
- bump the version of the main package.json file and all the derived ones [notice: TBD the versioning strategy]
- prepare the cloned folders to be released as NPM packages
- release each target package to NPM
  - TBD if we need to check that the use has already done a login and has the right permissions
- delete the cloned dist folder

The script will be split in multiple files, containing specific functions/modules, collected under the "release-parts" folder

*/