name: Compile Flight binary
on:
  workflow_dispatch:

jobs:
  compile_flight:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: '^1.16.5' # The Go version to download (if necessary) and use.

      - name: Compile Flight
        working-directory: ./export-go
        run: go build -ldflags "-X 'main.flightVersion=$(date -u '+%Y%m%d.%H%M%S')'"

      - name: Open a PR
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: 'new flight-export binary'
          title: 'New flight-export binary'
          body: ''