name: Build Flight iconset
on:
  workflow_dispatch:

jobs:
  build_iconset:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: export-go
    steps:
      - uses: actions/checkout@v2

      - name: Run flight
        env:
          FIGMA_TOKEN: ${{ secrets.FIGMA_TOKEN }}
          FLIGHT_FILE_ID: ${{ secrets.FLIGHT_FILE_ID }}
        run: ./flight

      - name: Open a PR
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: 'updated export of flight icons'
          title: 'Updated export of icons from Figma'
          body: ''
